apps/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    from apps.repository_list.views import repository_list_bp
    from apps.dashboard.views import dashboard_bp
    from apps.login.views import login_bp
    
    app.register_blueprint(repository_list_bp)
    app.register_blueprint(dashboard_bp)
    app.register_blueprint(login_bp)
    return app

apps/dashboard/views.py
from array import *
import random
from flask import Blueprint, render_template, request
from github import Github
import datetime as DT
from datetime import timedelta as TD

dashboard_bp = Blueprint("dashboard", __name__, url_prefix="/dashboard")

todayDate = DT.date.today()
todayDT = DT.datetime.now()


def last_seven_days_pos(x):
    diff = (todayDate - x).days

    return (6-diff)
        
##### Method end

commitsDay0 = 0
day0 = (todayDT - TD(days=6)).strftime("%d-%m-%Y")
commitsDay1 = 0
day1 = (todayDT - TD(days=5)).strftime("%d-%m-%Y")
commitsDay2 = 0
day2 = (todayDT - TD(days=4)).strftime("%d-%m-%Y")
commitsDay3 = 0
day3 = (todayDT - TD(days=3)).strftime("%d-%m-%Y")
commitsDay4 = 0
day4 = (todayDT - TD(days=2)).strftime("%d-%m-%Y")
commitsDay5 = 0
day5 = (todayDT - TD(days=1)).strftime("%d-%m-%Y")
commitsDay6 = 0
day6 = todayDT.strftime("%d-%m-%Y")

def formatArrayForReturn(x0, x1, x2, x3, x4, x5, x6):
    tuple0 = (day0, x0)
    tuple1 = (day1, x1)
    tuple2 = (day2, x2)
    tuple3 = (day3, x3)
    tuple4 = (day4, x4)
    tuple5 = (day5, x5)
    tuple6 = (day6, x6)
    formattedTupleArray = [tuple0, tuple1, tuple2, tuple3, tuple4, tuple5, tuple6]

    return formattedTupleArray


def getCommitsFromLast7Days(username, repoInput):
    g = Github('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')
    user = g.get_user(username)
    user.login

    global commitsDay0, commitsDay1, commitsDay2, commitsDay3, commitsDay4, commitsDay5, commitsDay6
    commitsDay0 = 0
    commitsDay1 = 0
    commitsDay2 = 0
    commitsDay3 = 0
    commitsDay4 = 0
    commitsDay5 = 0
    commitsDay6 = 0

    ## go through repos
    for repo in user.get_repos():

        ## if repo matches selected repository
        if repo.name == repoInput:

            # we access the commit
            for commit in repo.get_commits():

                # if a commit is made by the logged-in user
                if commit.author == user: 

                    #we access the date the commit was made
                    commitDate = commit.commit.author.date

                    #turn it into a datetime object
                    date1 = DT.date(commitDate.year, commitDate.month, commitDate.day)

                    # check whether it was made within the last seven days
                    # last seven_days_pos returns 0 if the change was made 6 days ago, 1 if it was made 5 days ago, etc.
                    # last_seven_days_pos max return value is 6 <-- last index in the array to return
                    day_in_array = last_seven_days_pos(date1)

                    # check if commit was made within the last seven days
                    if (day_in_array >=0):

                        ## adding commits to counts per day
                        match day_in_array:
                            case 0:
                                commitsDay0 += 1
                            case 1:
                                commitsDay1 += 1
                            case 2:
                                commitsDay2 += 1
                            case 3:
                                commitsDay3 += 1
                            case 4:
                                commitsDay4 += 1
                            case 5:
                                commitsDay5 += 1
                            case 6:
                                commitsDay6 += 1
                            case _:
                                continue
            break

    ## forming the array to return
    commitsPerDay = formatArrayForReturn(commitsDay0, commitsDay1, commitsDay2, commitsDay3, commitsDay4, commitsDay5, commitsDay6)

    return commitsPerDay


def getRepoLanguages(repoName,username):
    g = Github('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')
    user = g.get_user(username)
    user.login
    
    try:
        repo = user.get_repo(repoName)
    except:
        print("Error: Repo not found")
        return
    line_count = ([], [])
    langsDict = repo.get_languages()
    for language in langsDict.keys():
        line_count[0].append(language)
        line_count[1].append(langsDict[language])
    return line_count
#### Method end

@dashboard_bp.route("/")
def graph():
    nameWithRepo = request.args.get("value")
    spaceIndex = nameWithRepo.find(" ")
    
    username = nameWithRepo[0:spaceIndex]
    repoName = nameWithRepo[spaceIndex+1:]
    
    
    data1 = getCommitsFromLast7Days(username, repoName)

    labels1 = [row[0] for row in data1]
    values1 = [row[1] for row in data1]
 

    # DOESNT WORK 
    labels2,values2 = getRepoLanguages(repoName,username)
    
    colorPalette = []
    
    for _ in range(len(labels2)):
        rgb = 'rgb(' + str(round(random.random() *255)) + ',' + str(round(random.random() *255)) + ',' + str(round(random.random() *255)) + ')'
        colorPalette.append(rgb)
    
    
    return render_template("dashboard/graph.html", labels1 = labels1, values1 = values1,labels2 = labels2, values2 = values2, username = username, repoName = repoName, colorList = colorPalette)

apps/login/views.py
from flask import Blueprint, render_template

login_bp = Blueprint("login", __name__, url_prefix="/")

@login_bp.route("/")
def login():
    error=""
    return render_template("login.html",error=error)

apps/repository_list/views.py
from flask import Blueprint, render_template, request, abort
from github import Github
import random

repository_list_bp = Blueprint("repository_list", __name__, url_prefix="/repository_list")


class UserInfo:
    def __init__(self, username, oauthToken):
        self.username = username
        self.oauthToken = oauthToken


# def getUserRepos(user):
#     repoCount = 0
#     repoNames = []

#     for repo in user.get_repos():
#         repoCount += 1
#         repoNames.append(repo.name)

#     ## returns array with repo names
#     return repoNames

@repository_list_bp.errorhandler(400)
def page_not_found(error):
    error = "error: enter a valid username"
    return render_template('login.html', error=error)

def getCommitsInRepo(user):
    user.login
    repoNames = []
    countOfCommitsInRepo = []
    currentCountOfCommits = 0
    countOfRepos = 0

    for repo in user.get_repos():
        repoNames.append(repo.name)
        countOfRepos += 1
        currentCountOfCommits = 0
        for commit in repo.get_commits():
            currentCountOfCommits += 1
        countOfCommitsInRepo.append(currentCountOfCommits)

    formattedRepoArray = []
    for x in range(countOfRepos):
        tupleX = (repoNames[x], countOfCommitsInRepo[x])
        formattedRepoArray.append(tupleX)
    return formattedRepoArray, repoNames

##### Get breakdown of repos by language
def getLanguageBreakdown(user):
    user.login
    language_count = ([], [])
    for repo in user.get_repos():
        print(repo)
        languages = repo.get_languages()
        for language in languages.keys():
            if language not in language_count[0]:
                language_count[0].append(language)
                language_count[1].append(1)
            else:
                language_count[1][language_count[0].index(language)] += 1

    return language_count
##### Method end

@repository_list_bp.route("/")
def showList():
    
    user_info = UserInfo(
        request.args.get("username"),
        request.args.get("oauthToken")
    )
    
    
    g = Github('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')
    try:
        user = g.get_user(user_info.username)
    except Exception:
        abort(400)
        
    user.login
    
    data2, repoNames = getCommitsInRepo(user)
    
    
    
    
    labels2 = [row[0] for row in data2]
    values2 = [row[1] for row in data2]
    
    labels3,values3 = getLanguageBreakdown(user)
    
    colorPalette = []
    
    for _ in range(len(labels3)):
        rgb = 'rgb(' + str(round(random.random() *255)) + ',' + str(round(random.random() *255)) + ',' + str(round(random.random() *255)) + ')'
        colorPalette.append(rgb)
    
    
    # repoNames = getUserRepos(user)
    
    return render_template("repository_list/repository.html", data = repoNames, username = user_info.username, labels2 = labels2, values2 = values2, labels3 = labels3, values3 = values3, colorList = colorPalette)

apps/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block style %}
    {% endblock style %}
    <link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='css/base.css') }}">

    <title>{% block title %}My Page{%endblock%}</title>
</head>
<body>
    <header>
        <div class="headbar">
        {% include "header.html" %}
        </div>
        {% block sidebar %}
        {% endblock sidebar %}
    </header>
    
    {% block content %}
    {% endblock %}
</body>
</html>

apps/templates/dashboard/graph.html
{% extends "base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='css/graph2.css') }}">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
{% endblock style %}

{% block title %}
Graph
{% endblock title %}

{% block content %}

<div class="info">
    <h1>Repository: {{ repoName }}</h1>
</div>


<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div class="line_card">
    <canvas id = "lineChart"></canvas>
</div>

<div class="pie_card">
    <canvas id = "pieChart"></canvas>
</div>


<script>
    Chart.defaults.color = '#d1d1d1';
    var ctx = document.getElementById("lineChart").getContext("2d");
    var gradient = ctx.createLinearGradient(0, 0, 0, 400);
    gradient.addColorStop(0, "#e14ecb61");
    gradient.addColorStop(0.5, "#e14ecb33");
    gradient.addColorStop(1, "#e14ecb01");
    var lineChart = new Chart(ctx, {
        type: "line",
        data: {
            labels: {{ labels1 | safe }},
            datasets: [
                {
                    label: "Commits",
                    data: {{ values1 | safe }},
                    backgroundColor: gradient,
                    fill: true,
                    borderColor: "#e14eca",
                    lineTension: 0.1
                }
            ]
        },

        options: {
            plugins: {
                title: {
                    display: true,
                    text: 'The number of commits you have made in repositories over the last 7 days',
                    font: {
                        size: 20
                    }
                }
            },

            scales: {
                y: {
                    ticks: {color: "#d1d1d1", beginAtZero: true},
                },

                x: {
                    ticks: {color: "#d1d1d1"},
                    grid: {
                        color: "#e14ecb21"
                    }
                }
            },

            maintainAspectRatio: false

        }
    });

    let colorPalette = {{colorList | safe}};
    var ctx = document.getElementById("pieChart").getContext("2d");
    var pieChart = new Chart(ctx, {
        type: "pie",
        data: {
            labels: {{ labels2 | safe }},
            datasets: [
                {
                    label: "Lines",
                    data: {{ values2 | safe }},
                    fill: true,
                    backgroundColor: colorPalette,
                    borderColor: "#fff",
                    borderWidth: 3
                }
            ]
        },

        options: {
            plugins: {
                title: {
                    display: true,
                    text: 'The spread of languages used in your repository',
                    font: {
                        size: 20
                    },
                    padding: {
                        bottom: 30
                    }
                },

                legend: {
                    position: "left",
                    labels: {
                        font: {
                            size: 16
                        },
                        padding: 15
                    }
                }
            },

            maintainAspectRatio: false
        }
    });
</script>


{% endblock content %}

apps/templates/header.html
<div class="title">CSU33012 SWENG Main Project</div>
<div class="logout">
        <a href = "{{url_for('login.login')}}">Log out</a>
</div>

apps/templates/login.html
{% extends "base.html" %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/login.css') }}">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
{% endblock style %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<form action="{{ url_for('repository_list.showList') }}">
    <div class="screen-1">
        <div class="username">
            <label for="username" class="label">Username</label>
            <div>
                <input type="username" name="username" placeholder="test" />
            </div>
        </div>
        <div class="password">
            <label for="password" class="label">OAuth Token</label>
            <div>
                <input class="pas" type="password" name="oauthToken" placeholder="············" />
            </div>
        </div>
        <button class="login" type="submit">
            Log in
        </button>
        <div class="error">
            <p>{{error}}</p>
        </div>
    </div>
</form>
{% endblock content %}

apps/templates/repository_list/repository.html
{% extends "base.html" %}


{% block style %}
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='css/repository_list.css') }}">
<link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='css/graph.css') }}">
{% endblock style %}

{% block title %}
Repositry_list
{% endblock title %}

{% block sidebar %}

<nav id="sidebarMenu" class="sidebar">
    <div class="list-group mx-3 mt-4">
        <form action="{{ url_for('dashboard.graph') }}">
            <div class="list-group-hover">
                {% for value in data %}
                    <button class="list-group-item list-group-item-action py-2" type="submit" name="value" value="{{username}} {{value}}">
                            <span>{{value}}</span>
                    </button>
                {%endfor%}
        </form>
        
    </div>
</nav>

{% endblock sidebar %}

{% block content %}



<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div class="bar_card">
    <canvas id = "barChart"></canvas>
</div>

<div class="pie_card">
    <canvas id = "pieChart"></canvas>
</div>

<script>
    Chart.defaults.color = '#d1d1d1';
    var ctx = document.getElementById("barChart").getContext("2d");
    var barChart = new Chart(ctx, {
        type: "bar",
        data: {
            labels: {{ labels2 | safe }},
            datasets: [
                {
                    label: "Commits",
                    data: {{ values2 | safe }},
                    fill: true,
                    backgroundColor: "#1d8bf842",
                    borderColor: "#1d8cf8",
                    borderWidth: 3
                }
            ]
        },

        options: {
            plugins: {
                title: {
                    display: true,
                    text: 'Lets take a look at the amount of commits you have made in your repositories.',
                    font: {
                        size: 20
                    }
                }
            },

            indexAxis: 'y',
            scales: {
                y: {
                    ticks: {
                        color: "#d1d1d1", 
                        beginAtZero: true, 
                        font: {
                            size: 16
                        }
                    },
                    grid: {
                        color: "#1d8bf829"
                    }
                },

                x: {
                    ticks: {color: "#d1d1d1"},
                    grid: {
                        color: "#1d8bf829"
                    }
                }
            },

            maintainAspectRatio: false
        }
    });



    let colorPalette = {{colorList | safe}};
    var ctx = document.getElementById("pieChart").getContext("2d");
    var pieChart = new Chart(ctx, {
        type: "pie",
        data: {
            labels: {{ labels3 | safe }},
            datasets: [
                {
                    label: "Occurences",
                    data: {{ values3 | safe }},
                    fill: true,
                    backgroundColor: colorPalette,
                    borderColor: "#fff",
                    borderWidth: 3
                }
            ]
        },

        options: {
            plugins: {
                title: {
                    display: true,
                    text: 'The number of your repositories with a Langauage',
                    font: {
                        size: 20
                    },
                    padding: {
                        bottom: 30
                    }
                },

                legend: {
                    position: "left",
                    labels: {
                        font: {
                            size: 16
                        },
                        padding: 15
                    }
                }
            },

            maintainAspectRatio: false
        }
    });
</script>

{% endblock content %}